apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trino
  name: trino
  namespace: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trino
    spec:
      containers:
      - image: trinodb/trino
        name: trino
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "2048Mi"
            cpu: "750m"
          limits:
            memory: "4096Mi"
            cpu: "1500m" 

