apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: trino
  name: trinosvc
  namespace: trino
spec:
  ports:
  - name: 32766-8080
    nodePort: 32766
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: trino
  type: NodePort
